var MultiPollFormConstants = {
  ADD_POLL: "ADD_POLL",
  DELETE_POLL: "DELETE_POLL",
  ADD_ANSWER_CHOICE: "ADD_ANSWER_CHOICE",
  DELETE_ANSWER_CHOICE: "DELETE_ANSWER_CHOICE",
  UPDATE_POLL_QUESTION: "UPDATE_POLL_QUESTION",
  UPDATE_ANSWER_CHOICE: "UPDATE_ANSWER_CHOICE"
};

module.exports = MultiPollFormConstants;
