var PollConstants = {
  CHECK_POLLS: "CHECK_POLLS",
  UNCHECK_POLLS: "UNCHECK_POLLS",
  RECEIVE_EDIT_POLL_DATA: "RECEIVE_EDIT_POLL_DATA",
  UNCHECK_ALL: "UNCHECK_ALL"
};

module.exports = PollConstants;
