# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48f21bad110404fa114dff04e8120d071e465e2a4bda07ab7550a3d242dde8693815ec09d7ec170373fadd5b6f7eae23064f78d233e611c9a377660656034bdd

test:
  secret_key_base: bb68155e0a9c2a556e913e09279fae170415d1fc3deb0f5504d18d20bdb2ea78a09122e3dc01b620ac7c4d32b590640ac0b83e64766e932dcf3aaf329cff656b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
